#ifndef HYDRA_VERSION_H
#define HYDRA_VERSION_H

#define HYDRA_VERSION_MAJOR 0
#define HYDRA_VERSION_MINOR 1
#define HYDRA_VERSION_PATCH 0
#define HYDRA_VERSION_STRING "0.1.0"

#endif /* HYDRA_VERSION_H */
